repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
     - id: check-yaml
     - id: end-of-file-fixer
     - id: trailing-whitespace
     - id: check-added-large-files
       # The notebooks in this path go through nbstrip_full filter
       exclude: "^notebooks/.*.ipynb$"
  - repo: local
    hooks:
     - id: isort
       name: isort
       language: system
       entry: uv run isort
    #  - id: black
    #    name: black
    #    language: system
    #    entry: uv run black
     - id: ruff
       name: ruff-check
       language: system
       entry: uv run ruff check
       types_or: [ python, pyi, jupyter ]
       args: [ --fix ]
     - id: ruff-format
       name: ruff-format
       language: system
       entry: uv run ruff format
       types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
     - id: shellcheck
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.3
    hooks:
      # Update the uv lockfile
      - id: uv-lock
      - id: uv-export
