[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "autoshop"
authors = [
    {name = "Josie"},
]
description = "Python package to help with grocery shopping"
readme = "README.md"
requires-python = ">=3.11"
dynamic = ["version"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
